stages:
  # - build
  # - test
  # - sonarqube
  - deploy


# build:
#   stage: build
#   image: docker:18.09.7
#   services:
#     - docker:18.09.7-dind
#   variables:
#     DOCKER_TLS_CERTDIR: ""
#   before_script:
#     - docker login -u "$CI_REGISTRY_USER" -p "$CI_REGISTRY_PASSWORD" $CI_REGISTRY
#   script:
#     - |
#       if [[ "$CI_COMMIT_BRANCH" == "$CI_DEFAULT_BRANCH" ]]; then
#         tag=""
#         echo "Running on default branch '$CI_DEFAULT_BRANCH': tag = 'latest'"
#       else
#         tag=":$CI_COMMIT_REF_SLUG"
#         echo "Running on branch '$CI_COMMIT_BRANCH': tag = $tag"
#       fi
#     - docker build -t "$CI_REGISTRY_IMAGE${tag}" .
#     - docker push "$CI_REGISTRY_IMAGE${tag}"
#   rules:
#     - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH
#     - if: $CI_COMMIT_BRANCH == "develop"


# test:
#   stage: test
#   image: docker/compose:debian-1.29.2
#   services:
#     - docker:dind
#   variables:
#     DOCKER_TLS_CERTDIR: ""
#   script:
#     - docker-compose --profile test -f unitTests/docker-compose.yml --env-file unitTests/.env up --abort-on-container-exit
#   artifacts:
#     paths:
#       - cov_profile.lcov
#   rules:
#     - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH
#     - if: $CI_COMMIT_BRANCH == "develop"


# sonarqube:
#   stage: sonarqube
#   image:
#     name: sonarsource/sonar-scanner-cli:latest
#     entrypoint: [ "" ]
#   variables:
#     SONAR_USER_HOME: "${CI_PROJECT_DIR}/.sonar"  # Defines the location of the analysis task cache
#     GIT_DEPTH: "0"  # Tells git to fetch all the branches of the project, required by the analysis task
#   cache:
#     key: "${CI_JOB_NAME}"
#     paths:
#       - .sonar/cache
#   script:
#     - sonar-scanner -Dsonar.qualitygate.wait=true -Dsonar.projectKey=${SONAR_PROJECTKEY} -Dsonar.javascript.lcov.reportPaths="cov_profile.lcov"
#   allow_failure: true
#   needs:
#     - test
#   rules:
#     - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH
#     - if: $CI_COMMIT_BRANCH == "develop"


deploy-dev:
  stage: deploy
  image: ubuntu
  variables:
    DESTINATION_SSH_URL: ssh://ubuntu@$DESTINATION_HOST
  before_script:
    # Prepare ssh to destination host
    - 'which ssh-agent || ( apt-get update -y && apt-get install openssh-client -y )'
    - eval $(ssh-agent -s)
    - echo "$SSH_PRIVATE_KEY" | tr -d '\r' | ssh-add - > /dev/null
    - mkdir -p ~/.ssh
    - chmod 700 ~/.ssh
    - ssh-keyscan -t rsa $DESTINATION_HOST >> ~/.ssh/known_hosts
  script:
    - |
      if [[ "$CI_COMMIT_BRANCH" == "$CI_DEFAULT_BRANCH" ]]; then
        tag=""
        echo "Running on default branch '$CI_DEFAULT_BRANCH': tag = 'latest'"
      else
        tag=":$CI_COMMIT_REF_SLUG"
        echo "Running on branch '$CI_COMMIT_BRANCH': tag = $tag"
      fi
    - ssh $DESTINATION_SSH_URL "docker login -u gitlab-ci-token -p $CI_JOB_TOKEN $CI_REGISTRY"
    - ssh $DESTINATION_SSH_URL "docker pull $CI_REGISTRY_IMAGE${tag}"
    - ssh $DESTINATION_SSH_URL "docker-compose -p snowballr_dev -f project/develop/docker-compose.yml --env-file project/develop/.env --profile all up -d --force-recreate backend"
  # needs:
  #   - build
  rules:
    - if: $CI_COMMIT_BRANCH == "develop"


deploy-prod:
  stage: deploy
  image: ubuntu
  variables:
    DESTINATION_SSH_URL: ssh://ubuntu@$DESTINATION_HOST
  before_script:
    # Prepare ssh to destination host
    - 'which ssh-agent || ( apt-get update -y && apt-get install openssh-client -y )'
    - eval $(ssh-agent -s)
    - echo "$SSH_PRIVATE_KEY" | tr -d '\r' | ssh-add - > /dev/null
    - mkdir -p ~/.ssh
    - chmod 700 ~/.ssh
    - ssh-keyscan -t rsa $DESTINATION_HOST >> ~/.ssh/known_hosts
  script:
    - |
      if [[ "$CI_COMMIT_BRANCH" == "$CI_DEFAULT_BRANCH" ]]; then
        tag=""
        echo "Running on default branch '$CI_DEFAULT_BRANCH': tag = 'latest'"
      else
        tag=":$CI_COMMIT_REF_SLUG"
        echo "Running on branch '$CI_COMMIT_BRANCH': tag = $tag"
      fi
    # login to the gitlab container repository
    - ssh $DESTINATION_SSH_URL "docker login -u gitlab-ci-token -p $CI_JOB_TOKEN $CI_REGISTRY"
    - ssh $DESTINATION_SSH_URL "docker pull $CI_REGISTRY_IMAGE${tag}"
    - ssh $DESTINATION_SSH_URL "docker-compose -p snowballr -f project/master/docker-compose.yml --env-file project/master/.env --profile all up -d --force-recreate backend"
  # needs:
  #   - build
  rules:
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH
