# Configuration for project snowballr-backend, connector repository2

# Learn more about the Teamscale IDE Configuration File Format at
# <https://docs.teamscale.com/reference/teamscale-toml/>.

version = "1.0"

root = true

[server]
url = "https://exia.informatik.uni-ulm.de/teamscale/"

[project]
id = "snowballr-backend"
