services:
    # PostgreSQL Database
    db:
        image: postgres:16.1-alpine3.19
        restart: always
        environment:
            POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
        ports:
            - "5432:5432"
        volumes:
            - ./db-data:/var/lib/postgresql/data
        healthcheck:
            test: "pg_isready -U postgres"
            start_period: 2s # wait 2s to let db get ready for accepting connections
            start_interval: 2s # start first healthcheck after 2s
        networks:
            - db_network
        profiles: ["", "db-only", "registry"]

    # Use local backend
    backend-local:
        build:
            context: .
        environment:
            PORT: ${PORT:-8080}
            LOG_LEVEL: ${LOG_LEVEL:-DEBUG}
            DATABASE_PASSWORD: ${DATABASE_PASSWORD}
            DATABASE_HOST: db # use db service as db host
        ports:
            - ${PORT:-8080}:${PORT:-8080}
        depends_on:
            db:
                condition: service_healthy
        networks:
            - db_network
            - grpc_network
        profiles: [""]

    proxy-local:
        build:
            context: .
            dockerfile: Dockerfile.proxy
        ports:
            - "${WEB_PORT:-8081}:${WEB_PORT:-8081}"
        command:
            # Point to the backend service name within the Docker network
            - --backend_addr=backend-local:${PORT:-8080}
            - --allow_all_origins # Crucial for local dev where frontend is on different origin
            - --run_tls_server=false # Don't require TLS
            - --server_http_debug_port=${WEB_PORT:-8081} # Proxy listens on this port inside the container
        depends_on:
            - backend-local
        networks:
            - grpc_network
        profiles: [""]

    # Use the published backend with the specified tag
    backend-registry:
        image: ghcr.io/se-uulm/snowballr-backend:${BACKEND_TAG:-latest-dev}
        environment:
            PORT: ${PORT:-8080}
            LOG_LEVEL: ${LOG_LEVEL:-DEBUG}
            DATABASE_PASSWORD: ${DATABASE_PASSWORD}
            DATABASE_HOST: db # use db service as db host
        ports:
            - ${PORT:-8080}:${PORT:-8080}
        depends_on:
            db:
                condition: service_healthy
        networks:
            - db_network
            - grpc_network
        profiles: ["registry"]

    proxy-registry:
        build:
            context: .
            dockerfile: Dockerfile.proxy
        ports:
            - "${WEB_PORT:-8081}:${WEB_PORT:-8081}"
        command:
            # Point to the backend service name within the Docker network
            - --backend_addr=backend-registry:${PORT:-8080}
            - --allow_all_origins # Crucial for local dev where frontend is on different origin
            - --run_tls_server=false # Don't require TLS
            - --server_http_debug_port=${WEB_PORT:-8081} # Proxy listens on this port inside the container
        depends_on:
            - backend-registry
        networks:
            - grpc_network
        profiles: ["registry"]

networks:
    db_network:
        driver: bridge
    grpc_network:
        driver: bridge
