version: "3.7"
services:
  # Postgres sql database server only visible by pgadmin and backend services
  postgresdb:
    image: postgres
    expose:
      - "5432"
    volumes:
      - ${POSTGRES_PATH}:/var/lib/postgresql/
    environment:
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    logging:
      driver: ${POSTGRES_LOGGING}
  # Environment container for hosting backend deno typescript application
  backend:
    image: hayd/ubuntu-deno
    command: test --allow-env --allow-net --coverage=cov-profile --unstable
    ports:
      - "8000:8000"
    volumes:
      - ${BACKEND_PATH}:/app/
    environment: 
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    depends_on:
      - postgresdb