package se.uulm.snowballr.backend.openapi

import io.mockk.every
import io.mockk.mockk
import kotlinx.serialization.json.Json
import kotlinx.serialization.json.JsonElement
import org.junit.jupiter.api.AfterAll
import org.junit.jupiter.api.Assertions.assertEquals
import org.junit.jupiter.api.Assertions.assertTrue
import org.junit.jupiter.api.BeforeAll
import org.junit.jupiter.api.Tag
import org.junit.jupiter.api.Test
import org.koin.core.context.startKoin
import org.koin.core.context.stopKoin
import org.koin.dsl.module
import org.springframework.beans.factory.annotation.Autowired
import org.springframework.boot.test.context.SpringBootTest
import org.springframework.boot.webmvc.test.autoconfigure.AutoConfigureMockMvc
import org.springframework.test.web.servlet.MockMvc
import org.springframework.test.web.servlet.request.MockMvcRequestBuilders.get
import org.springframework.test.web.servlet.result.MockMvcResultMatchers.status
import se.uulm.snowballr.backend.auth.IAuthenticationManager
import se.uulm.snowballr.backend.auth.ICookieManager
import se.uulm.snowballr.backend.auth.IJwtManager
import se.uulm.snowballr.backend.env.Env
import se.uulm.snowballr.backend.env.EnvReader
import se.uulm.snowballr.backend.openapi.OpenApiContractTest.Companion.COMMITTED_SPEC
import se.uulm.snowballr.backend.rest.SnowballRApplication
import se.uulm.snowballr.backend.service.IAuthenticationService
import se.uulm.snowballr.backend.service.IProjectService
import java.io.File

/**
 * Emits the code-first OpenAPI specification on build.
 *
 * The specification is generated by springdoc from the REST controllers and served at the configured
 * `springdoc.api-docs.path`. This test fetches it, writes the canonical form to [COMMITTED_SPEC] (the artifact
 * consumed by the OpenAPI TypeScript client generator).
 *
 * The full application context is deliberately pinned to [SnowballRApplication], whose component scan is
 * confined to the `rest` package, so the context is cheap to start. It still needs Koin running, though: `KoinBridge`
 * exposes the Koin-backed services as Spring beans, and `SecurityConfig` requires them eagerly at startup. Rather
 * than pulling in the real database-backed module, a minimal Koin module of mocks is started for the lifetime of
 * this class - just enough to satisfy the bean wiring without touching a database.
 */
@SpringBootTest(classes = [SnowballRApplication::class])
@AutoConfigureMockMvc
@Tag("openapi")
class OpenApiContractTest(@Autowired private val mvc: MockMvc) {
    @Test
    fun `When the API spec is generated, then it is not blank and written to a committed file`() {
        val generated = canonicalize(fetchOpenApiSpec())

        val committedSpec = File(COMMITTED_SPEC)
        committedSpec.parentFile.mkdirs()

        val previous = committedSpec.takeIf { it.exists() }?.readText()
        if (previous != generated) {
            committedSpec.writeText(generated)
        }

        assertEquals(generated, committedSpec.readText())
        assertTrue(generated.isNotBlank())
    }

    /**
     * Fetches the OpenAPI specification from the springdoc endpoint.
     */
    private fun fetchOpenApiSpec(): String = mvc.perform(get(API_DOCS_PATH))
        .andExpect(status().isOk)
        .andReturn()
        .response
        .getContentAsString(Charsets.UTF_8)

    /**
     * Normalizes the specification into a stable, diff-friendly form: the result is pretty-printed with a fixed
     * indentation.
     */
    private fun canonicalize(raw: String): String =
        JSON.encodeToString(JsonElement.serializer(), JSON.parseToJsonElement(raw)) + "\n"

    private companion object {
        /** Path the springdoc api-docs endpoint is served at (see `application.properties`). */
        const val API_DOCS_PATH = "/api-docs"

        /** Committed specification the build is checked against. */
        const val COMMITTED_SPEC = "api/openapi.json"

        val JSON: Json = Json {
            prettyPrint = true
            prettyPrintIndent = "    "
        }

        /**
         * Starts Koin with mocks before the Spring context is created, since `KoinBridge` and `SecurityConfig`
         * resolve Koin-backed beans eagerly during context refresh. Auth bypass is stubbed on so the security
         * filter never exercises [IAuthenticationManager] or [ICookieManager].
         */
        @JvmStatic
        @BeforeAll
        fun startTestKoin() {
            val miscellaneous = mockk<Env.Miscellaneous>()
            every { miscellaneous.authBypassEnabled } returns true

            val env = mockk<Env>()
            every { env.miscellaneous } returns miscellaneous

            val envReader = mockk<EnvReader>()
            every { envReader.env } returns env

            startKoin {
                modules(
                    module {
                        single<IProjectService> { mockk() }
                        single<IAuthenticationService> { mockk() }
                        single<IAuthenticationManager> { mockk() }
                        single<ICookieManager> { mockk() }
                        single<EnvReader> { envReader }
                    },
                )
            }
        }

        @JvmStatic
        @AfterAll
        fun stopTestKoin() = stopKoin()
    }
}
