package se.uulm.snowballr.backend.grpc.interceptor

import io.github.oshai.kotlinlogging.KotlinLogging
import io.grpc.Context
import io.grpc.ForwardingServerCall.SimpleForwardingServerCall
import io.grpc.ForwardingServerCallListener.SimpleForwardingServerCallListener
import io.grpc.Metadata
import io.grpc.ServerCall
import io.grpc.ServerCallHandler
import io.grpc.ServerInterceptor
import io.grpc.Status
import se.uulm.snowballr.backend.context.RequestContext

private val logger = KotlinLogging.logger {}

private const val SLOW_CALL_THRESHOLD_MS = 2_000L

/**
 * gRPC [Context] key used to hand the short correlation ID generated by the [loggingInterceptor] over to
 * the [authenticationInterceptor], so the [RequestContext] it builds reuses the same ID. This keeps
 * interceptor-level logs and service-level logs of a single call correlated under one `requestId`.
 */
internal val REQUEST_ID_CONTEXT_KEY: Context.Key<String> = Context.key("requestId")

/**
 * A [ServerInterceptor] that assigns a short random request ID to every gRPC call, logs the call entry and
 * its outcome (status and duration), and warns about slow calls.
 *
 * The request ID is placed on the gRPC [Context] (via [REQUEST_ID_CONTEXT_KEY]) so downstream interceptors
 * can adopt it, and mirrored into the SLF4J MDC around each log statement it emits so the `logback.xml`
 * pattern can render it. Service-level logs pick up the same ID through the [RequestContext] installed by
 * the [authenticationInterceptor].
 */
val loggingInterceptor =
    object : ServerInterceptor {
        override fun <ReqT, RespT> interceptCall(
            call: ServerCall<ReqT?, RespT?>?,
            headers: Metadata?,
            next: ServerCallHandler<ReqT?, RespT?>?,
        ): ServerCall.Listener<ReqT?>? {
            val requestId = RequestContext.generateRequestId()
            val startTime = System.currentTimeMillis()
            val methodName = call?.run { methodDescriptor.fullMethodName } ?: "<unknown method>"
            val context = Context.current().withValue(REQUEST_ID_CONTEXT_KEY, requestId)

            return context.call {
                RequestContext.withRequestIdMdc(requestId) { logger.debug { "Received call to $methodName" } }
                val statusCall = call?.let { StatusCapturingCall(it) }
                val listener = next?.startCall(statusCall, headers) ?: return@call null
                RequestLoggingListener(listener, requestId, methodName, startTime, statusCall)
            }
        }
    }

/**
 * Wraps a [ServerCall.Listener] to log the call's duration once it completes or is canceled, warning when
 * it exceeds [SLOW_CALL_THRESHOLD_MS].
 *
 * Timing starts when the call is intercepted, so the measured duration covers authentication and validation
 * as well as the service method itself, and calls canceled before the client half-closes are still logged.
 */
private class RequestLoggingListener<ReqT>(
    delegate: ServerCall.Listener<ReqT>,
    private val requestId: String,
    private val methodName: String,
    private val startTime: Long,
    private val statusCall: StatusCapturingCall<*, *>?,
) : SimpleForwardingServerCallListener<ReqT>(delegate) {
    override fun onComplete() {
        super.onComplete()
        logOutcome("completed")
    }

    override fun onCancel() {
        super.onCancel()
        logOutcome("cancelled")
    }

    private fun logOutcome(outcome: String) {
        val durationMs = System.currentTimeMillis() - startTime
        val statusCode = statusCall?.closedStatus?.code?.name ?: "<not closed>"
        RequestContext.withRequestIdMdc(requestId) {
            logger.debug { "$methodName $outcome with $statusCode in ${durationMs}ms" }
            if (durationMs >= SLOW_CALL_THRESHOLD_MS) {
                logger.warn { "Slow call: $methodName took ${durationMs}ms (threshold: ${SLOW_CALL_THRESHOLD_MS}ms)" }
            }
        }
    }
}

/**
 * Wraps a [ServerCall] to record the [Status] the call is eventually closed with, so that
 * [RequestLoggingListener] can report it alongside the duration.
 *
 * This interceptor is the outermost one, so its wrapper is the last to see `close` and therefore observes
 * the status after the [exceptionInterceptor] has mapped any exception onto it. That interceptor logs the
 * severity of a failed call, so the outcome line here stays at `DEBUG` for every status.
 */
private class StatusCapturingCall<ReqT, RespT>(
    delegate: ServerCall<ReqT, RespT>,
) : SimpleForwardingServerCall<ReqT, RespT>(delegate) {
    @Volatile
    var closedStatus: Status? = null
        private set

    override fun close(status: Status?, trailers: Metadata?) {
        closedStatus = status
        super.close(status, trailers)
    }
}
