package se.uulm.snowballr.backend.grpc.interceptor

import io.github.oshai.kotlinlogging.KotlinLogging
import io.grpc.Context
import io.grpc.ForwardingServerCallListener.SimpleForwardingServerCallListener
import io.grpc.Metadata
import io.grpc.ServerCall
import io.grpc.ServerCallHandler
import io.grpc.ServerInterceptor
import org.slf4j.MDC
import se.uulm.snowballr.backend.context.RequestContext

private val logger = KotlinLogging.logger {}

private const val SLOW_CALL_THRESHOLD_MS = 2_000L

/**
 * gRPC [Context] key used to hand the short correlation ID generated by the [loggingInterceptor] over to
 * the [authenticationInterceptor], so the [RequestContext] it builds reuses the same ID. This keeps
 * interceptor-level logs and service-level logs of a single call correlated under one `requestId`.
 */
internal val REQUEST_ID_CONTEXT_KEY: Context.Key<String> = Context.key("requestId")

/**
 * A [ServerInterceptor] that assigns a short random request ID to every gRPC call, logs the call entry and
 * completion, and warns about slow calls.
 *
 * The request ID is placed on the gRPC [Context] (via [REQUEST_ID_CONTEXT_KEY]) so downstream interceptors
 * can adopt it, and mirrored into the SLF4J [MDC] around each log statement it emits so the `logback.xml`
 * pattern can render it. Service-level logs pick up the same ID through the [RequestContext] installed by
 * the [authenticationInterceptor].
 */
val loggingInterceptor =
    object : ServerInterceptor {
        override fun <ReqT, RespT> interceptCall(
            call: ServerCall<ReqT?, RespT?>?,
            headers: Metadata?,
            next: ServerCallHandler<ReqT?, RespT?>?,
        ): ServerCall.Listener<ReqT?>? {
            val requestId = RequestContext.generateRequestId()
            val methodName = call?.run { methodDescriptor.fullMethodName } ?: "<unknown method>"
            val context = Context.current().withValue(REQUEST_ID_CONTEXT_KEY, requestId)

            return context.call {
                withRequestIdMdc(requestId) { logger.debug { "Received call to $methodName" } }
                val listener = next?.startCall(call, headers) ?: return@call null
                RequestLoggingListener(listener, requestId, methodName)
            }
        }
    }

/**
 * Wraps a [ServerCall.Listener] to log the call's duration once it completes or is cancelled, warning when
 * it exceeds [SLOW_CALL_THRESHOLD_MS]. Timing starts at [onHalfClose], the point where the grpc-kotlin
 * coroutine that runs the service method is launched.
 */
private class RequestLoggingListener<ReqT>(
    delegate: ServerCall.Listener<ReqT>,
    private val requestId: String,
    private val methodName: String,
) : SimpleForwardingServerCallListener<ReqT>(delegate) {
    private var halfCloseTime: Long = 0L

    override fun onHalfClose() {
        halfCloseTime = System.currentTimeMillis()
        super.onHalfClose()
    }

    override fun onComplete() {
        super.onComplete()
        logDuration()
    }

    override fun onCancel() {
        super.onCancel()
        logDuration()
    }

    private fun logDuration() {
        if (halfCloseTime == 0L) return
        val durationMs = System.currentTimeMillis() - halfCloseTime
        withRequestIdMdc(requestId) {
            logger.debug { "$methodName completed in ${durationMs}ms" }
            if (durationMs >= SLOW_CALL_THRESHOLD_MS) {
                logger.warn { "Slow call: $methodName took ${durationMs}ms (threshold: ${SLOW_CALL_THRESHOLD_MS}ms)" }
            }
        }
    }
}

/**
 * Runs [block] with [requestId] set in the SLF4J [MDC], restoring the previous value afterward. Used for
 * interceptor log lines that run outside the [RequestContext]-managed service coroutine.
 */
private inline fun withRequestIdMdc(requestId: String, block: () -> Unit) {
    val previous = MDC.get(RequestContext.MDC_REQUEST_ID_KEY)
    MDC.put(RequestContext.MDC_REQUEST_ID_KEY, requestId)
    try {
        block()
    } finally {
        if (previous == null) {
            MDC.remove(RequestContext.MDC_REQUEST_ID_KEY)
        } else {
            MDC.put(RequestContext.MDC_REQUEST_ID_KEY, previous)
        }
    }
}
