name: Build

on:
    push:
        branches: ["develop"]
        tags: ["v*.*.*"]
    pull_request:

jobs:
    build-jar:
        name: Building the application as jar file
        runs-on: ubuntu-latest
        steps:
            - name: Checkout repository
              uses: actions/checkout@v7
              with:
                  fetch-depth: 0
                  fetch-tags: true

            - name: Setup Java and Gradle
              uses: ./.github/workflows/setup-java-gradle/

            - name: Build the jar file
              run: ./gradlew shadowJar --stacktrace

            - name: Upload jar file
              uses: actions/upload-artifact@v7
              with:
                  name: snowballr-backend-jar
                  path: build/libs/*.jar
                  if-no-files-found: error

    release:
        name: Release
        needs: build-jar
        if: github.ref_type == 'tag'
        permissions:
            contents: write
        uses: SE-UUlm/snowballr-ci/.github/workflows/release.yml@v1
        with:
            artifact-name: snowballr-backend-jar
            asset-path: snowballr-backend-*.jar
            target-branch: main
