name: Build

on:
    push:
        branches: ["develop"]
        tags: ["v*.*.*"]
    pull_request:

env:
    java_version: ${{ vars.JAVA_VERSION }}
    java_distribution: ${{ vars.JAVA_DISTRIBUTION }}

jobs:
    build-jar:
        name: Building the application as jar file
        runs-on: ubuntu-latest
        steps:
            - name: Checkout repository
              uses: actions/checkout@v6

            - name: Setup
              uses: ./.github/workflows/setup/
              with:
                  java_version: ${{ env.java_version }}
                  java_distribution: ${{ env.java_distribution }}

            - name: Build the jar file
              run: ./gradlew shadowJar --stacktrace

            - name: Upload jar file
              uses: actions/upload-artifact@v5
              with:
                  name: snowballr-backend-jar
                  path: build/libs/*.jar
                  if-no-files-found: error

    release:
        name: Release
        needs: build-jar
        if: github.ref_type == 'tag'
        permissions:
            contents: write
        uses: SE-UUlm/snowballr-ci/.github/workflows/release.yml@v1.0.0
        with:
            artifact-name: snowballr-backend-jar
            asset-path: snowballr-backend-*.jar
            target-branch: main
