name: Code Quality Checks

on:
    push:
        branches:
            - main
            - develop
    pull_request:
    workflow_dispatch:

env:
    java_version: ${{ vars.JAVA_VERSION }}
    java_distribution: ${{ vars.JAVA_DISTRIBUTION }}

jobs:
    formatting:
        name: Check for valid formatting
        runs-on: ubuntu-latest
        steps:
            - name: Checkout repository
              uses: actions/checkout@v4
              with:
                  submodules: "recursive"

            - name: Setup
              uses: ./.github/workflows/setup/
              with:
                  java_version: ${{ env.java_version }}
                  java_distribution: ${{ env.java_distribution }}

            - name: Check formatting
              run: ./gradlew lintKotlin

    linting:
        name: Check for linting errors
        runs-on: ubuntu-latest
        steps:
            - name: Checkout repository
              uses: actions/checkout@v4
              with:
                  submodules: "recursive"

            - name: Setup
              uses: ./.github/workflows/setup/
              with:
                  java_version: ${{ env.java_version }}
                  java_distribution: ${{ env.java_distribution }}

            - name: Check linting
              run: ./gradlew detekt

    testing:
        name: Run tests
        runs-on: ubuntu-latest
        permissions:
            pull-requests: write
            contents: read
        steps:
            - name: Checkout repository
              uses: actions/checkout@v4
              with:
                  submodules: "recursive"

            - name: Setup
              uses: ./.github/workflows/setup/
              with:
                  java_version: ${{ env.java_version }}
                  java_distribution: ${{ env.java_distribution }}

            - name: Run tests and collect coverage
              run: |
                  ./gradlew test
                  ./gradlew koverPrintCoverage

            - name: Upload report
              if: failure() || success()
              uses: actions/upload-artifact@v4
              with:
                  name: test-report
                  path: |
                      build/testReportHtml
                      build/coverageHtml
                  if-no-files-found: error

            - name: Add coverage to PR
              if: failure() || success()
              uses: madrapps/jacoco-report@v1.7.2
              with:
                  paths: ${{ github.workspace }}/build/coverageXml/report.xml
                  token: ${{ secrets.GITHUB_TOKEN }}
                  title: Code Coverage
                  update-comment: true

            # We have to trigger this job on "pull_request" so that the coverage is commented in the PR,
            # but Teamscale requires a revision. Therefore, we retrieve the latest commit and set the revision manually.
            - name: Retrieve latest commit of PR
              if: ${{ github.event_name == 'pull_request' }}
              run: |
                  # Fetch commits of PR
                  response=$(curl --request GET \
                      --url 'https://api.github.com/repos/${{ github.repository }}/pulls/${{ github.event.pull_request.number }}/commits' \
                      --header 'Accept: application/vnd.github.v3+json' \
                      --header 'Content-Type: application/json')
                  # Store response in JSON file and retrieve SHA of latest commit
                  echo $response > response.json
                  length=$(jq 'length' response.json)
                  index=$(($length - 1))
                  latest_commit=$(jq --argjson index $index '.[$index]' response.json)
                  latest_commit_sha=$(echo "$latest_commit" | jq -r '.sha')
                  echo "Latest Commit SHA: $latest_commit_sha"
                  echo "LATEST_COMMIT_SHA=$latest_commit_sha" >> $GITHUB_ENV

            - name: Teamscale Upload
              uses: cqse/teamscale-upload-action@v2.9.6
              with:
                  server: "https://exia.informatik.uni-ulm.de/teamscale"
                  project: "29382a84-6015-4ecd-b7dd-7f578cae4040"
                  user: "slartibartfass2"
                  accesskey: ${{ secrets.TEAMSCALE_ACCESS_KEY }}
                  partition: "Github Action > ${{ github.ref_name }} ${{ github.run_id }}"
                  format: JACOCO
                  message: "Code coverage from GitHub Actions"
                  files: ${{ github.workspace }}/build/coverageXml/report.xml
                  # When the event is a PR, use the previously defined env variable; otherwise the `github.sha` is fine.
                  revision: ${{ github.event_name == 'pull_request' && env.LATEST_COMMIT_SHA || github.sha }}
