name: Code Quality Checks

on:
    push:
        branches:
            - main
            - develop
    pull_request:
    workflow_dispatch:

jobs:
    linting:
        name: Check for linting errors
        runs-on: ubuntu-latest
        steps:
            - name: Checkout repository
              uses: actions/checkout@v6

            - name: Setup Java and Gradle
              uses: ./.github/workflows/setup-java-gradle/

            - name: Check linting
              run: ./gradlew lint

    unit-testing:
        name: Run unit tests
        runs-on: ubuntu-latest
        permissions:
            pull-requests: write
            contents: read
        steps:
            - name: Checkout repository
              uses: actions/checkout@v6

            - name: Setup Java and Gradle
              uses: ./.github/workflows/setup-java-gradle/

            - name: Setup Python and uv
              uses: ./.github/workflows/setup-python-uv/

            - name: Run tests and collect coverage
              run: ./gradlew test

            - name: Upload report
              if: failure() || success()
              uses: actions/upload-artifact@v7
              with:
                  name: unit-test-report
                  path: |
                      build/testReportHtml
                      build/coverageHtml
                  if-no-files-found: error

            - name: Add coverage to PR
              if: failure() || success()
              uses: madrapps/jacoco-report@v1.7.2
              with:
                  paths: ${{ github.workspace }}/build/coverageXml/report.xml
                  token: ${{ secrets.GITHUB_TOKEN }}
                  title: Code Coverage
                  update-comment: true

            - name: Upload coverage report
              uses: actions/upload-artifact@v7
              with:
                  name: coverage-report
                  path: ${{ github.workspace }}/build/coverageXml/report.xml
                  retention-days: 1
                  if-no-files-found: error

    integration-testing:
        name: Run integration tests
        runs-on: ubuntu-latest
        steps:
            - name: Checkout repository
              uses: actions/checkout@v6

            - name: Setup Java and Gradle
              uses: ./.github/workflows/setup-java-gradle/

            - name: Setup Python and uv
              uses: ./.github/workflows/setup-python-uv/

            - name: Run integration tests
              run: ./gradlew integrationTest

            - name: Upload report
              if: failure() || success()
              uses: actions/upload-artifact@v7
              with:
                  name: integration-test-report
                  path: build/integrationTestReportHtml
                  if-no-files-found: error

    teamscale-upload:
        name: Teamscale Upload
        runs-on: ubuntu-latest
        needs: unit-testing
        steps:
            - name: Checkout repository
              uses: actions/checkout@v6
              with:
                  fetch-depth: 0

            - name: Download coverage report
              uses: actions/download-artifact@v8
              with:
                  name: coverage-report
                  path: .

            - name: Teamscale Upload
              uses: SE-UUlm/snowballr-ci/src/teamscale-upload@v1
              with:
                  project: "29382a84-6015-4ecd-b7dd-7f578cae4040"
                  access-key: ${{ secrets.TEAMSCALE_ACCESS_KEY }}
                  format: JACOCO
                  files: ${{ github.workspace }}/report.xml

    sonarqube:
        name: SonarQube Analysis
        if: github.ref_name == 'develop' && github.ref_type == 'branch'
        runs-on: ubuntu-latest
        needs: unit-testing
        steps:
            - name: Checkout repository
              uses: actions/checkout@v6
              with:
                  fetch-depth: 0

            - name: Setup Java and Gradle
              uses: ./.github/workflows/setup-java-gradle/

            - name: Download coverage report
              uses: actions/download-artifact@v8
              with:
                  name: coverage-report
                  path: ${{ github.workspace }}/build/coverageXml

            - name: SonarQube Scan
              run: ./gradlew sonar -x test --stacktrace
              env:
                  SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
                  SONAR_HOST_URL: ${{ secrets.SONAR_HOST_URL }}
