name: Code Quality Checks

on:
    push:
        branches:
            - main
            - develop
    pull_request:
    workflow_dispatch:

env:
    java_version: ${{ vars.JAVA_VERSION }}
    java_distribution: ${{ vars.JAVA_DISTRIBUTION }}

jobs:
    linting:
        name: Check for linting errors
        runs-on: ubuntu-latest
        steps:
            - name: Checkout repository
              uses: actions/checkout@v6

            - name: Setup
              uses: ./.github/workflows/setup/
              with:
                  java_version: ${{ env.java_version }}
                  java_distribution: ${{ env.java_distribution }}

            - name: Check linting
              run: ./gradlew lint

    testing:
        name: Run tests
        runs-on: ubuntu-latest
        permissions:
            pull-requests: write
            contents: read
        steps:
            - name: Checkout repository
              uses: actions/checkout@v6

            - name: Setup
              uses: ./.github/workflows/setup/
              with:
                  java_version: ${{ env.java_version }}
                  java_distribution: ${{ env.java_distribution }}

            - uses: actions/setup-python@v6
              with:
                  python-version: "3.13"
                  cach: "pip"

            - name: Install Python Plugin Fetcher Dependencies
              run: pip install -r ./requirements.txt

            - name: Run tests and collect coverage
              run: |
                  ./gradlew test
                  ./gradlew koverPrintCoverage

            - name: Upload report
              if: failure() || success()
              uses: actions/upload-artifact@v6
              with:
                  name: test-report
                  path: |
                      build/testReportHtml
                      build/coverageHtml
                  if-no-files-found: error

            - name: Add coverage to PR
              if: failure() || success()
              uses: madrapps/jacoco-report@v1.7.2
              with:
                  paths: ${{ github.workspace }}/build/coverageXml/report.xml
                  token: ${{ secrets.GITHUB_TOKEN }}
                  title: Code Coverage
                  update-comment: true

            - name: Upload coverage report
              uses: actions/upload-artifact@v6
              if: ${{ !cancelled() }}
              with:
                  name: coverage-report
                  path: ${{ github.workspace }}/build/coverageXml/report.xml
                  retention-days: 1
                  if-no-files-found: error

    teamscale-upload:
        name: Teamscale Upload
        runs-on: ubuntu-latest
        needs: testing
        steps:
            - name: Checkout repository
              uses: actions/checkout@v6
              with:
                  fetch-depth: 0

            - name: Download coverage report
              uses: actions/download-artifact@v7
              with:
                  name: coverage-report
                  path: .

            - name: Teamscale Upload
              uses: SE-UUlm/snowballr-ci/src/teamscale-upload@v1.0.0
              with:
                  project: "29382a84-6015-4ecd-b7dd-7f578cae4040"
                  access-key: ${{ secrets.TEAMSCALE_ACCESS_KEY }}
                  format: JACOCO
                  files: ${{ github.workspace }}/report.xml

    sonarqube:
        name: SonarQube Analysis
        runs-on: ubuntu-latest
        needs: testing
        steps:
            - name: Checkout repository
              uses: actions/checkout@v6
              with:
                  fetch-depth: 0

            - name: Setup
              uses: ./.github/workflows/setup/
              with:
                  java_version: ${{ env.java_version }}
                  java_distribution: ${{ env.java_distribution }}

            - name: Download coverage report
              uses: actions/download-artifact@v7
              with:
                  name: coverage-report
                  path: ${{ github.workspace }}/build/coverageXml

            - name: SonarQube Scan
              run: ./gradlew sonar -x test --stacktrace
              env:
                  SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
                  SONAR_HOST_URL: ${{ secrets.SONAR_HOST_URL }}
