name: Linting Changelog

on:
    pull_request:
        paths:
            - CHANGELOG.md

jobs:
    changelog-linting:
        name: Linting the changelog
        runs-on: ubuntu-latest
        steps:
            - name: Checkout code
              uses: actions/checkout@v5

            - name: Set up Node.js
              uses: actions/setup-node@v5
              with:
                  node-version: "22"

            - name: Install hallmark
              run: npm install -g hallmark

            - name: Lint CHANGELOG.md
              run: hallmark CHANGELOG.md

            - name: Check for broken references in CHANGELOG.md
              uses: becheran/mlc@v0.21.0
              with:
                  args: --ignore-links "https://github.com/SE-UUlm/snowballr-backend/releases/tag/*" CHANGELOG.md
